(function () {

    EC.Enums = EC.Enums || {};
    EC.Enums.DateType = {
        NotSet: 0,
        Second: 1,
        Minute: 2,
        Hour: 3,
        Day: 4
    };

    EC.Enums.HtmlAttributes = {
        _async: "async",
        _autocomplete: "autocomplete",
        _autofocus: "autofocus",
        _autoplay: "autoplay",
        _challenge: "challenge",
        _charset: "charset",
        _checked: "checked",
        _cite: "cite",
        _class: "class",
        _cols: "cols",
        _colspan: "colspan",
        _command: "command",
        _content: "content",
        _contenteditable: "contenteditable",
        _contextmenu: "contextmenu",
        _controls: "controls",
        _coords: "coords",
        _crossorigin: "crossorigin",
        _data: "data",
        _datetime: "datetime",
        _default: "default",
        _defer: "defer",
        _dir: "dir",
        _dirname: "dirname",
        _disabled: "disabled",
        _download: "download",
        _draggable: "draggable",
        _dropzone: "dropzone",
        _enctype: "enctype",
        _for: "for",
        _form: "form",
        _formaction: "formaction",
        _formenctype: "formenctype",
        _formmethod: "formmethod",
        _formnovalidate: "formnovalidate",
        _formtarget: "formtarget",
        _headers: "headers",
        _height: "height",
        _hidden: "hidden",
        _high: "high",
        _href: "href",
        _hreflang: "hreflang",
        _http_equiv: "http_equiv",
        _icon: "icon",
        _id: "id",
        _inputmode: "inputmode",
        _ismap: "ismap",
        _itemid: "itemid",
        _itemprop: "itemprop",
        _itemref: "itemref",
        _itemscope: "itemscope",
        _itemtype: "itemtype",
        _keytype: "keytype",
        _kind: "kind",
        _label: "label",
        _lang: "lang",
        _list: "list",
        _loop: "loop",
        _low: "low",
        _manifest: "manifest",
        _max: "max",
        _maxlength: "maxlength",
        _media: "media",
        _mediagroup: "mediagroup",
        _menu: "menu",
        _method: "method",
        _min: "min",
        _minlength: "minlength",
        _multiple: "multiple",
        _muted: "muted",
        _name: "name",
        _nonce: "nonce",
        _novalidate: "novalidate",
        _open: "open",
        _optimum: "optimum",
        _pattern: "pattern",
        _placeholder: "placeholder",
        _poster: "poster",
        _preload: "preload",
        _radiogroup: "radiogroup",
        _readonly: "readonly",
        _rel: "rel",
        _required: "required",
        _reversed: "reversed",
        _rows: "rows",
        _rowspan: "rowspan",
        _sandbox: "sandbox",
        _spellcheck: "spellcheck",
        _scope: "scope",
        _scoped: "scoped",
        _seamless: "seamless",
        _selected: "selected",
        _shape: "shape",
        _size: "size",
        _sizes: "sizes",
        _sortable: "sortable",
        _sorted: "sorted",
        _span: "span",
        _src: "src",
        _srcdoc: "srcdoc",
        _srclang: "srclang",
        _srcset: "srcset",
        _start: "start",
        _step: "step",
        _style: "style",
        _tabindex: "tabindex",
        _target: "target",
        _title: "title",
        _translate: "translate",
        _type: "type",
        _typemustmatch: "typemustmatch",
        _usemap: "usemap",
        _value: "value",
        _width: "width",
        _wrap: "wrap"
    };

    EC.Enums.MessageTypes = {
        default: "default",
        success: "success",
        warning: "warning",
        danger: "danger",
        info: "info"
    };

    EC.Enums.MessageState = {
        success: 1,
        warning: 2,
        info: 3,
        error: 4
    };

    EC.Enums.SortType = {
        asc: "asc",
        desc: "desc"
    };
})();